# Generated by Django 3.0.8 on 2020-07-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='start',
            new_name='stars',
        ),
    ]
